image: docker:git

stages:
  - build-docker

variables:
  IMAGE_FRONTEND: "terraqueodev/docker-develop-env"  
  REPO: "registry.gitlab.com"

build-image:
  services:
  - docker:19.03.5-dind
#  retry: 2
  before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REPO
  stage: build-docker
  script:
  - DOCKER_BUILDKIT=1 docker build . --target devops -t workspace-devops
  - DOCKER_BUILDKIT=1 docker build . --target node -t workspace-node
  - DOCKER_BUILDKIT=1 docker build . --build-arg STAGE_VERSION=code --build-arg INIT=init_code  --target devops -t workspace-devops-code
  - DOCKER_BUILDKIT=1 docker build . --build-arg STAGE_VERSION=code --build-arg INIT=init_code  --target node   -t workspace-node-code
  - docker tag workspace-devops $REPO/$IMAGE_FRONTEND:devops
  - docker push $REPO/$IMAGE_FRONTEND:devops  
  - docker tag workspace-devops-code $REPO/$IMAGE_FRONTEND:devops-code
  - docker push $REPO/$IMAGE_FRONTEND:devops-code    
  - docker tag workspace-node $REPO/$IMAGE_FRONTEND:node
  - docker push $REPO/$IMAGE_FRONTEND:node
  - docker tag workspace-node-code $REPO/$IMAGE_FRONTEND:node-code
  - docker push $REPO/$IMAGE_FRONTEND:node-code
  only:
      - master
